/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Products
         * @description Every product in SKU order; an unknown category is 422.
         */
        get: operations["list_products_api_catalog_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Regions
         * @description Each region's stores with their customer segment mix.
         */
        get: operations["list_regions_api_catalog_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/competitors/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Competitor Gaps
         * @description Competitor price index, gap and KVI undercut per SKU x region, widest gap first.
         *
         *     An unknown category is 422.
         */
        get: operations["competitor_gaps_api_competitors_gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inventory
         * @description Stock per SKU x region pooled over the region's stores, with overstock flags.
         *
         *     An unknown category, or a region without stores, is 422.
         */
        get: operations["inventory_api_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/retrain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retrain */
        post: operations["retrain_api_models_retrain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{session_id}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Plan
         * @description Re-simulate the session's latest plan revision and store the result against it.
         */
        post: operations["simulate_plan_api_plans__session_id__simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relations/{sku_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Relations */
        get: operations["get_relations_api_relations__sku_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BindingConstraint
         * @description A constraint that limits the plan: dropping it gives a strictly better objective, or,
         *     when time ran out, one that may.
         */
        BindingConstraint: {
            /** Category */
            category?: string | null;
            evidence: components["schemas"]["BindingEvidence"];
            kind: components["schemas"]["ConstraintKind"];
            /** Limit */
            limit: number;
            /** Objective Gain */
            objective_gain: number | null;
            region?: components["schemas"]["Region"] | null;
            /** Sku Id */
            sku_id?: string | null;
            source: components["schemas"]["ConstraintSource"];
        };
        /**
         * BindingEvidence
         * @description How sure the optimiser is that a constraint binds (ADR 0038).
         * @enum {string}
         */
        BindingEvidence: "exact" | "lower_bound" | "unproven";
        /**
         * ClearanceShortfall
         * @description A clearance target the plan misses: no plan within the other constraints reaches it,
         *     so the optimiser returned the plan that comes closest and reports by how much it falls
         *     short (SPEC §9.4, F-06 AC2, ADR 0040).
         */
        ClearanceShortfall: {
            /** Expected Sell Through */
            expected_sell_through: number;
            region: components["schemas"]["Region"];
            /** Shortfall Units */
            shortfall_units: number;
            /** Sku Id */
            sku_id: string;
            /** Target */
            target: number;
        };
        /**
         * ClearanceTarget
         * @description The minimum sell-through the brief asks for a SKU it names for clearance, in every
         *     region of the scope (ADR 0014, ADR 0040).
         */
        ClearanceTarget: {
            /** Sell Through */
            sell_through: number;
            /** Sku Id */
            sku_id: string;
        };
        /**
         * CompetitorGap
         * @description One SKU in one region against the competitor's latest price before the as-of week.
         */
        CompetitorGap: {
            /**
             * Base Price
             * @description Our regular shelf price in rupees.
             */
            base_price: number;
            /** Category */
            category: string;
            /**
             * Competitor On Promo
             * @description Whether that price was a competitor promo.
             */
            competitor_on_promo: boolean;
            /**
             * Competitor Price
             * @description The competitor's latest price in rupees.
             */
            competitor_price: number;
            /**
             * Cpi
             * @description Competitor price index: competitor price ÷ base price.
             */
            cpi: number;
            /**
             * Gap
             * @description 1 minus CPI: how much cheaper the competitor is (< 0: dearer).
             */
            gap: number;
            /** Is Kvi */
            is_kvi: boolean;
            /** Name */
            name: string;
            /**
             * Price Week
             * @description The week of that price, before the as-of week.
             */
            price_week: number;
            region: components["schemas"]["Region"];
            /** Sku Id */
            sku_id: string;
            /** Subcategory */
            subcategory: string;
            /**
             * Undercut
             * @description A KVI whose CPI is below 1 minus the undercut threshold.
             */
            undercut: boolean;
        };
        /**
         * CompetitorGaps
         * @description The gaps for a scope, widest first, with the company-policy rules they were judged by.
         */
        CompetitorGaps: {
            /** As Of Week */
            as_of_week: number;
            /** Gaps */
            gaps: components["schemas"]["CompetitorGap"][];
            /**
             * Kvi Price Tolerance
             * @description How far above the competitor a KVI promo price may sit, when enabled.
             */
            kvi_price_tolerance: number;
            /** Undercut Threshold */
            undercut_threshold: number;
        };
        /**
         * CompetitorReaction
         * @description The competitor-reaction scenario (F-09 AC2, ADR 0045): in each run, each plan line's
         *     competitor matches its discount with this probability, independently of the other lines.
         */
        CompetitorReaction: {
            /**
             * Match Probability
             * @description Chance, per plan line and run, that the competitor matches our discount.
             */
            match_probability: number;
        };
        /** Complement */
        Complement: {
            /**
             * Lift
             * @description P(both in a basket) / (P(one) x P(other)).
             */
            lift: number;
            /** Sku Id */
            sku_id: string;
            /** Std Error */
            std_error: number | null;
            /**
             * Support
             * @description Share of baskets holding both SKUs.
             */
            support: number;
            /**
             * Theta
             * @description Cross-price effect, or null if not estimable.
             */
            theta: number | null;
        };
        /**
         * ConstraintKind
         * @description A plan-level constraint the optimiser enforces (ADR 0036, ADR 0038).
         * @enum {string}
         */
        ConstraintKind: "marketing_budget" | "minimum_margin" | "margin_floor" | "max_promoted_skus" | "regional_budget" | "clearance_target" | "kvi_price_tolerance";
        /**
         * ConstraintSource
         * @description Who set a constraint: only the brief's constraints may be relaxed (ADR 0007).
         * @enum {string}
         */
        ConstraintSource: "brief" | "company_policy";
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /**
             * Brief
             * @description The brief, in plain English.
             */
            brief: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthChecks */
        HealthChecks: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
            /**
             * Model Registry
             * @enum {string}
             */
            model_registry: "ok" | "missing";
        };
        /** HealthResponse */
        HealthResponse: {
            checks: components["schemas"]["HealthChecks"];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
        };
        /** InventoryReport */
        InventoryReport: {
            /** As Of Week */
            as_of_week: number;
            /** Overstock Threshold Days */
            overstock_threshold_days: number;
            /** Snapshot Week */
            snapshot_week: number;
            /** Statuses */
            statuses: components["schemas"]["InventoryRow"][];
        };
        /** InventoryRow */
        InventoryRow: {
            /** Available Stock */
            available_stock: number;
            /** Category */
            category: string;
            /** Days Of Cover */
            days_of_cover: number;
            /** Is Overstock */
            is_overstock: boolean;
            /** Name */
            name: string;
            /** On Hand */
            on_hand: number;
            /** On Order */
            on_order: number;
            region: components["schemas"]["Region"];
            /** Safety Stock */
            safety_stock: number;
            /** Sku Id */
            sku_id: string;
        };
        /**
         * LineSimulation
         * @description One plan line's simulated ranges, identified by its SKU and region.
         */
        LineSimulation: {
            gross_profit: components["schemas"]["Percentiles"];
            margin: components["schemas"]["Percentiles"];
            promo_spend: components["schemas"]["Percentiles"];
            region: components["schemas"]["Region"];
            revenue: components["schemas"]["Percentiles"];
            sell_through: components["schemas"]["Percentiles"] | null;
            /** Sku Id */
            sku_id: string;
            /** Stockout Probability */
            stockout_probability: number;
            units: components["schemas"]["Percentiles"];
        };
        /**
         * Mechanism
         * @enum {string}
         */
        Mechanism: "PCT_OFF" | "BOGO" | "BUNDLE" | "FIXED_PRICE";
        /**
         * MechanismOption
         * @description One promo option's expected numbers, as its prediction gave them (rupees, units over
         *     its promo weeks; a BUNDLE's money fields include its partner).
         */
        MechanismOption: {
            /** Anchor Sku Id */
            anchor_sku_id: string;
            /** Basket Lift */
            basket_lift?: number | null;
            /** Cannibalised Profit */
            cannibalised_profit: number;
            /** Clearance Value */
            clearance_value: number;
            /** Effective Price */
            effective_price: number;
            /** Gross Profit */
            gross_profit: number;
            /** Halo Profit */
            halo_profit: number;
            /** Incremental Profit */
            incremental_profit: number;
            /** Margin */
            margin: number;
            option: components["schemas"]["PlanLine"];
            /** Partner Effective Price */
            partner_effective_price?: number | null;
            /** Partner Sku Id */
            partner_sku_id?: string | null;
            /** Promo Cost */
            promo_cost: number;
            /** Revenue */
            revenue: number;
            /** Units */
            units: number;
            /** Value */
            value: number;
        };
        /**
         * MechanismOutcome
         * @description One mechanism in a comparison: its best option, or why it has none.
         */
        MechanismOutcome: {
            best: components["schemas"]["MechanismOption"] | null;
            /**
             * Chosen
             * @default false
             */
            chosen: boolean;
            mechanism: components["schemas"]["Mechanism"];
            /**
             * Unavailable
             * @default []
             */
            unavailable: components["schemas"]["PruneReason"][];
        };
        /**
         * ModelEntry
         * @description One registered model version; `live` marks the one the API is serving.
         */
        ModelEntry: {
            /** As Of Week */
            as_of_week: number;
            kind: components["schemas"]["ModelKind"];
            /** Live */
            live: boolean;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /**
             * Trained At
             * Format: date-time
             */
            trained_at: string;
            /** Version */
            version: number;
        };
        /**
         * ModelKind
         * @enum {string}
         */
        ModelKind: "demand" | "relations";
        /**
         * ModelList
         * @description Registered models, newest first.
         */
        ModelList: {
            /** Models */
            models: components["schemas"]["ModelEntry"][];
        };
        /**
         * ModelVersion
         * @description The registered model that produced the numbers, so a plan can be traced to it.
         */
        ModelVersion: {
            /** As Of Week */
            as_of_week: number;
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /** Version */
            version: number;
        };
        /**
         * NotSelectedOption
         * @description The best option of a SKU and region with no plan line, and why it was left out.
         */
        NotSelectedOption: {
            /**
             * Cannibalises
             * @default []
             */
            cannibalises: string[];
            option: components["schemas"]["PlanLine"];
            /** Reasons */
            reasons: components["schemas"]["NotSelectedReason"][];
            /** Value */
            value: number;
        };
        /**
         * NotSelectedReason
         * @description Why a promo option is not in the plan: a rule it breaks alone or added to the plan.
         * @enum {string}
         */
        NotSelectedReason: "low_uplift" | "out_of_stock" | "breaks_policy" | "over_budget" | "over_regional_budget" | "breaks_margin" | "max_promoted_skus" | "misses_clearance_target" | "breaks_kvi_tolerance" | "cannibalises" | "time_limit";
        /**
         * Percentiles
         * @description The 10th, 50th and 90th percentiles of one simulated metric across the runs.
         */
        Percentiles: {
            /** P10 */
            p10: number;
            /** P50 */
            p50: number;
            /** P90 */
            p90: number;
        };
        /**
         * PlanLine
         * @description A promo option selected into a promo plan: one (SKU, region) decision (ADR 0004).
         */
        PlanLine: {
            /** Bundle Partner Sku Id */
            bundle_partner_sku_id?: string | null;
            /** Depth Pct */
            depth_pct: number;
            /** Duration Weeks */
            duration_weeks: number;
            mechanism: components["schemas"]["Mechanism"];
            region: components["schemas"]["Region"];
            /** Sku Id */
            sku_id: string;
            /** Start Week */
            start_week: number;
            target_segment: components["schemas"]["TargetSegment"];
        };
        /**
         * PlanRevision
         * @description One numbered version of the promo plan within a planning session.
         */
        PlanRevision: {
            /**
             * Binding Constraints
             * @default []
             */
            binding_constraints: components["schemas"]["BindingConstraint"][];
            /**
             * Clearance Shortfalls
             * @default []
             */
            clearance_shortfalls: components["schemas"]["ClearanceShortfall"][];
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["PlanRevisionLine"][];
            /**
             * Not Selected
             * @default []
             */
            not_selected: components["schemas"]["NotSelectedOption"][];
            /** Number */
            number: number;
            /** Objective */
            objective?: number | null;
            /**
             * Policy Findings
             * @default []
             */
            policy_findings: components["schemas"]["PolicyFinding"][];
            simulation?: components["schemas"]["PlanSimulation"] | null;
            solver_status?: components["schemas"]["SolveStatus"] | null;
        };
        /**
         * PlanRevisionLine
         * @description A plan line with the expected numbers the planning tool computed for it (rupees).
         */
        PlanRevisionLine: {
            /** Expected Incremental Profit */
            expected_incremental_profit: number;
            /** Expected Units */
            expected_units: number;
            line: components["schemas"]["PlanLine"];
            /**
             * Mechanism Comparison
             * @default []
             */
            mechanism_comparison: components["schemas"]["MechanismOutcome"][];
            /** Promo Cost */
            promo_cost: number;
            why_chosen?: components["schemas"]["WhyChosen"] | null;
        };
        /**
         * PlanSimulation
         * @description What `simulate` returns for a promo plan, and what a plan revision stores.
         */
        PlanSimulation: {
            competitor_reaction?: components["schemas"]["CompetitorReaction"] | null;
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["LineSimulation"][];
            /** N Runs */
            n_runs: number;
            /**
             * Regions
             * @default []
             */
            regions: components["schemas"]["RegionStockout"][];
            /** Seed */
            seed: number;
            total: components["schemas"]["SimulatedOutcomes"];
        };
        /**
         * PlanSimulationResponse
         * @description A plan revision's new simulation, now stored against it in place of the old one.
         */
        PlanSimulationResponse: {
            /** As Of Week */
            as_of_week: number;
            demand_model: components["schemas"]["ModelVersion"];
            /** Revision Number */
            revision_number: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            simulation: components["schemas"]["PlanSimulation"];
        };
        /**
         * PlanningRequest
         * @description Money is in rupees (ADR 0015). The brief's optional constraints may only tighten
         *     company policy; a value that would loosen it is kept here as read, and planning applies
         *     the policy value instead and flags it (ADR 0007, ADR 0040).
         */
        PlanningRequest: {
            /** As Of Week */
            as_of_week: number;
            /**
             * Clearance Targets
             * @default []
             */
            clearance_targets: components["schemas"]["ClearanceTarget"][];
            /** Kvi Price Tolerance */
            kvi_price_tolerance?: number | null;
            /** Marketing Budget */
            marketing_budget: number;
            /** Max Promoted Skus Per Category Per Region */
            max_promoted_skus_per_category_per_region?: number | null;
            /** Min Margin */
            min_margin?: number | null;
            promo_window: components["schemas"]["PromoWindow"];
            /** Regional Budget Caps */
            regional_budget_caps?: {
                [key: string]: number;
            };
            scope: components["schemas"]["Scope"];
        };
        /**
         * PolicyFinding
         * @description A brief value that would loosen company policy: planning keeps the policy value and
         *     flags it (ADR 0007, ADR 0040).
         */
        PolicyFinding: {
            /** Applied */
            applied: number;
            /** Field */
            field: string;
            /** Message */
            message: string;
            /** Requested */
            requested: number;
        };
        /** Product */
        Product: {
            /** Base Price */
            base_price: number;
            /** Brand */
            brand: string;
            /** Category */
            category: string;
            /** Is Kvi */
            is_kvi: boolean;
            /** Name */
            name: string;
            /** Pack Size */
            pack_size: string;
            /** Sku Id */
            sku_id: string;
            /** Subcategory */
            subcategory: string;
            /** Unit Cost */
            unit_cost: number;
        };
        /** ProductList */
        ProductList: {
            /** Products */
            products: components["schemas"]["Product"][];
        };
        /**
         * PromoWindow
         * @description The future weeks, inclusive, in which a plan's promotions must start and end.
         */
        PromoWindow: {
            /** End Week */
            end_week: number;
            /** Start Week */
            start_week: number;
        };
        /**
         * PruneReason
         * @description Why option generation dropped an enumerated promo option, in the order the rules are
         *     applied (ADR 0035).
         * @enum {string}
         */
        PruneReason: "no_charm_price" | "max_discount" | "below_cost" | "duplicate_price" | "stock" | "partner_stock";
        /**
         * Region
         * @enum {string}
         */
        Region: "North" | "South" | "East" | "West";
        /** RegionList */
        RegionList: {
            /** Regions */
            regions: components["schemas"]["RegionStores"][];
        };
        /** RegionStockout */
        RegionStockout: {
            region: components["schemas"]["Region"];
            /** Stockout Probability */
            stockout_probability: number;
        };
        /** RegionStores */
        RegionStores: {
            region: components["schemas"]["Region"];
            /** Stores */
            stores: components["schemas"]["Store"][];
        };
        /**
         * RelationsResponse
         * @description A SKU's substitutes (strongest first) and complements (highest lift first).
         */
        RelationsResponse: {
            /** Complements */
            complements: components["schemas"]["Complement"][];
            model: components["schemas"]["ModelVersion"];
            /** Sku Id */
            sku_id: string;
            /** Substitutes */
            substitutes: components["schemas"]["Substitute"][];
        };
        /**
         * Scope
         * @description The regions and categories a planning request covers, optionally narrowed to SKUs.
         */
        Scope: {
            /** Categories */
            categories: string[];
            /** Regions */
            regions: components["schemas"]["Region"][];
            /**
             * Sku Ids
             * @default []
             */
            sku_ids: string[];
        };
        /**
         * Segment
         * @description A behavioural customer group; never defined by protected attributes.
         * @enum {string}
         */
        Segment: "Value Seekers" | "Families" | "Premium" | "Young Urban";
        /** SelectionReason */
        SelectionReason: {
            /** Amount */
            amount: number;
            code: components["schemas"]["SelectionReasonCode"];
        };
        /**
         * SelectionReasonCode
         * @description A positive part of a plan line's value (ADR 0005, ADR 0035), or the clearance target it
         *     helps meet (ADR 0040).
         * @enum {string}
         */
        SelectionReasonCode: "incremental_profit" | "clearance_value" | "halo" | "clearance_target";
        /** SessionCreated */
        SessionCreated: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /**
         * SessionResponse
         * @description One planning session's read model: status, brief, planning request, latest revision.
         */
        SessionResponse: {
            /** Brief */
            brief: string;
            /** Error */
            error: string | null;
            plan_revision: components["schemas"]["PlanRevision"] | null;
            planning_request: components["schemas"]["PlanningRequest"] | null;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["SessionStatus"];
        };
        /**
         * SessionStatus
         * @description Every status a planning session can have. E3 uses planning, awaiting_approval, failed.
         * @enum {string}
         */
        SessionStatus: "planning" | "awaiting_clarification" | "awaiting_approval" | "approved" | "rejected" | "failed";
        /**
         * SimulatePlanRequest
         * @description Re-simulate a session's latest plan revision (ADR 0043), optionally against a
         *     competitor reaction (ADR 0045). The seed is configuration.
         */
        SimulatePlanRequest: {
            /** @description The competitor-reaction scenario; omit or null for a competitor that never reacts. */
            competitor_reaction?: components["schemas"]["CompetitorReaction"] | null;
            /**
             * N Runs
             * @description Runs to simulate; omit for the configured default (SIMULATION_RUNS).
             */
            n_runs?: number | null;
        };
        /**
         * SimulatedOutcomes
         * @description Ranges over the promo weeks, units capped at pooled available stock (ADR 0004, 0011).
         *
         *     Units and sell-through are the anchor SKU's; revenue, gross profit and promo spend
         *     include a BUNDLE's partner (ADR 0017). Margin is gross profit over revenue in each run
         *     (0 in a run with no revenue). Sell-through is None when there is no available stock.
         */
        SimulatedOutcomes: {
            gross_profit: components["schemas"]["Percentiles"];
            margin: components["schemas"]["Percentiles"];
            promo_spend: components["schemas"]["Percentiles"];
            revenue: components["schemas"]["Percentiles"];
            sell_through: components["schemas"]["Percentiles"] | null;
            units: components["schemas"]["Percentiles"];
        };
        /**
         * SolveStatus
         * @enum {string}
         */
        SolveStatus: "OPTIMAL" | "FEASIBLE" | "INFEASIBLE";
        /** Store */
        Store: {
            /** City */
            city: string;
            /** Segment Mix */
            segment_mix: {
                [key: string]: number;
            };
            /** Store Id */
            store_id: string;
        };
        /** Substitute */
        Substitute: {
            /** Q Value */
            q_value: number;
            /** Sku Id */
            sku_id: string;
            /** Std Error */
            std_error: number;
            /**
             * Theta
             * @description Cross-price effect: positive for a substitute.
             */
            theta: number;
        };
        /**
         * TargetSegment
         * @description Who a plan line is offered to: one segment exclusively, or All customers (ADR 0006).
         * @enum {string}
         */
        TargetSegment: "Value Seekers" | "Families" | "Premium" | "Young Urban" | "All customers";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WhyChosen
         * @description Why a plan line was chosen: the positive parts of its value, what it is worth alone,
         *     and whether it is the best option the optimiser could pick for its SKU and region.
         */
        WhyChosen: {
            /** Best For Sku Region */
            best_for_sku_region: boolean;
            /** Reasons */
            reasons: components["schemas"]["SelectionReason"][];
            /** Value */
            value: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_products_api_catalog_products_get: {
        parameters: {
            query?: {
                category?: string | null;
                kvi_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_regions_api_catalog_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionList"];
                };
            };
        };
    };
    competitor_gaps_api_competitors_gaps_get: {
        parameters: {
            query?: {
                /** @description Defaults to the data's default as-of week. */
                as_of_week?: number | null;
                region?: components["schemas"]["Region"] | null;
                category?: string | null;
                kvi_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitorGaps"];
                };
            };
            /** @description No data is loaded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    inventory_api_inventory_get: {
        parameters: {
            query?: {
                /** @description Defaults to the data's default as-of week. */
                as_of_week?: number | null;
                region?: components["schemas"]["Region"] | null;
                category?: string | null;
                overstocked_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryReport"];
                };
            };
            /** @description No data is loaded for the week */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
        };
    };
    retrain_api_models_retrain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelEntry"];
                };
            };
            /** @description A retrain is running or no data */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    simulate_plan_api_plans__session_id__simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulatePlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSimulationResponse"];
                };
            };
            /** @description Unknown session, or a session without a plan revision yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The latest demand model cannot simulate the stored plan */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No trained demand model, or no inventory snapshot for the planning request's as-of week */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_relations_api_relations__sku_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationsResponse"];
                };
            };
            /** @description No such SKU */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No relations model fitted on the live demand model */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unknown session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
