/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Products
         * @description Every product in SKU order; an unknown category is 422.
         */
        get: operations["list_products_api_catalog_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Regions
         * @description Each region's stores with their customer segment mix.
         */
        get: operations["list_regions_api_catalog_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/competitors/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Competitor Gaps
         * @description Competitor price index, gap and KVI undercut per SKU x region, widest gap first.
         *
         *     An unknown category is 422.
         */
        get: operations["competitor_gaps_api_competitors_gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_api_evals_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inventory
         * @description Stock per SKU x region pooled over the region's stores, with overstock flags.
         *
         *     An unknown category, or a region without stores, is 422.
         */
        get: operations["inventory_api_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/retrain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retrain */
        post: operations["retrain_api_models_retrain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{session_id}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Plan
         * @description Re-simulate the session's latest plan revision and store the result against it.
         */
        post: operations["simulate_plan_api_plans__session_id__simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relations/{sku_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Relations */
        get: operations["get_relations_api_relations__sku_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/amend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Amend Session
         * @description Amend the planning request (AG-05); a new plan revision, with its diff from the
         *     previous one, is planned in the background.
         */
        post: operations["amend_session_api_sessions__session_id__amend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Session
         * @description Approve the session's latest plan revision, which makes it final (SF-04).
         */
        post: operations["approve_session_api_sessions__session_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/clarify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clarify Session
         * @description Answer the open clarification questions; planning resumes in the background.
         */
        post: operations["clarify_session_api_sessions__session_id__clarify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Events
         * @description The session's trace events over SSE (SF-01, ADR 0047), in order, as they happen.
         *
         *     Each event's SSE `id` is its number in the session; a client that reconnects with
         *     `Last-Event-ID` gets the events after it, with no gaps or repeats (a missing or
         *     non-numeric one replays the trace from the start). Once the session is final
         *     (approved, or failed) the stream sends `event: end` with its status and closes.
         */
        get: operations["session_events_api_sessions__session_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Session
         * @description Reject the session's latest plan revision with a reason; the session stays open.
         */
        post: operations["reject_session_api_sessions__session_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AmendRequest
         * @description Amend the planning request of a session awaiting approval or rejected (ADR 0052): in
         *     plain English, or by accepting the latest revision's relaxation. Exactly one of the two.
         */
        AmendRequest: {
            /**
             * Accept Relaxation
             * @description Accept the latest plan revision's smallest relaxation (ADR 0044) as the amendment instead of writing one.
             * @default false
             */
            accept_relaxation: boolean;
            /**
             * Text
             * @description The change, in plain English ("cut budget to ₹6 lakh", "drop West").
             */
            text?: string | null;
        };
        /**
         * Amendment
         * @description A change to the planning request, in the manager's words, made while a plan revision
         *     waited for a decision (AG-05, ADR 0052). Every amendment is kept, oldest first.
         */
        Amendment: {
            /**
             * Amended At
             * Format: date-time
             */
            amended_at: string;
            /** Amends Revision */
            amends_revision: number;
            relaxation?: components["schemas"]["Relaxation"] | null;
            /** Text */
            text: string;
        };
        /**
         * ApproveRequest
         * @description Approve a plan revision: it must be the session's latest (ADR 0046).
         */
        ApproveRequest: {
            /**
             * Revision Number
             * @description The plan revision being approved.
             */
            revision_number: number;
        };
        /**
         * Assumption
         * @description One planning-request field (or a fact the plan relies on) as the agent read or inferred
         *     it: its value in words, where it came from and how sure the agent is (ADR 0048).
         */
        Assumption: {
            /** Confidence */
            confidence: number;
            /**
             * Fallback
             * @default false
             */
            fallback: boolean;
            /** Field */
            field: string;
            /**
             * Flagged
             * @default false
             */
            flagged: boolean;
            /** Note */
            note?: string | null;
            source: components["schemas"]["AssumptionSource"];
            /** Value */
            value: string;
        };
        /**
         * AssumptionSource
         * @description Where an assumed value came from.
         * @enum {string}
         */
        AssumptionSource: "brief" | "data" | "default";
        /**
         * BestPlanSummary
         * @description The best plan (ADR 0063): our optimiser run on true-parameter predictions.
         */
        BestPlanSummary: {
            /** Lines */
            lines: number;
            /** Objective */
            objective: number | null;
            /** Sku Ids */
            sku_ids: string[];
            solver_status: components["schemas"]["SolveStatus"];
        };
        /**
         * BindingConstraint
         * @description A constraint that limits the plan: dropping it gives a strictly better objective, or,
         *     when time ran out, one that may.
         */
        BindingConstraint: {
            /** Category */
            category?: string | null;
            evidence: components["schemas"]["BindingEvidence"];
            kind: components["schemas"]["ConstraintKind"];
            /** Limit */
            limit: number;
            /** Objective Gain */
            objective_gain: number | null;
            region?: components["schemas"]["Region"] | null;
            /** Sku Id */
            sku_id?: string | null;
            source: components["schemas"]["ConstraintSource"];
        };
        /**
         * BindingEvidence
         * @description How sure the optimiser is that a constraint binds (ADR 0038).
         * @enum {string}
         */
        BindingEvidence: "exact" | "lower_bound" | "unproven" | "infeasible";
        /**
         * Breach
         * @description A constraint the plan's true outcome breaks, by the oracle (ADR 0012).
         * @enum {string}
         */
        Breach: "promo_cost_over_budget" | "margin_below_minimum" | "demand_over_stock";
        /**
         * Clarification
         * @description A question the agent asked and the manager's answer, in their own words.
         */
        Clarification: {
            /** Answer */
            answer: string;
            question: components["schemas"]["ClarificationQuestion"];
        };
        /**
         * ClarificationAsked
         * @description The Context agent paused to ask the manager these questions.
         */
        ClarificationAsked: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "clarification";
            /** Questions */
            questions: string[];
        };
        /**
         * ClarificationCheck
         * @description Whether a vague or conflicting scenario's session asked about, or flagged, a field the
         *     scenario names (#55).
         */
        ClarificationCheck: {
            /** Asked */
            asked: string[];
            /** Flagged */
            flagged: string[];
            /** Named */
            named: string[];
            /** Passed */
            passed: boolean;
        };
        /**
         * ClarificationQuestion
         * @description A specific question the agent asks instead of guessing (AG-02).
         */
        ClarificationQuestion: {
            /** Field */
            field: string;
            /** Id */
            id: string;
            /** Question */
            question: string;
            reason: components["schemas"]["QuestionReason"];
            /**
             * Suggestions
             * @default []
             */
            suggestions: string[];
        };
        /**
         * ClarifyRequest
         * @description Answers to the session's open clarification questions (ADR 0048).
         */
        ClarifyRequest: {
            /**
             * Answers
             * @description An answer in plain English for every open question, keyed by its id.
             */
            answers: {
                [key: string]: string;
            };
        };
        /**
         * ClearanceShortfall
         * @description A clearance target the plan misses: no plan within the other constraints reaches it,
         *     so the optimiser returned the plan that comes closest and reports by how much it falls
         *     short (SPEC §9.4, F-06 AC2, ADR 0040).
         */
        ClearanceShortfall: {
            /** Expected Sell Through */
            expected_sell_through: number;
            region: components["schemas"]["Region"];
            /** Shortfall Units */
            shortfall_units: number;
            /** Sku Id */
            sku_id: string;
            /** Target */
            target: number;
        };
        /**
         * ClearanceTarget
         * @description The minimum sell-through the brief asks for a SKU it names for clearance, in every
         *     region of the scope (ADR 0014, ADR 0040).
         */
        ClearanceTarget: {
            /** Sell Through */
            sell_through: number;
            /** Sku Id */
            sku_id: string;
        };
        /**
         * CompetitorGap
         * @description One SKU in one region against the competitor's latest price before the as-of week.
         */
        CompetitorGap: {
            /**
             * Base Price
             * @description Our regular shelf price in rupees.
             */
            base_price: number;
            /** Category */
            category: string;
            /**
             * Competitor On Promo
             * @description Whether that price was a competitor promo.
             */
            competitor_on_promo: boolean;
            /**
             * Competitor Price
             * @description The competitor's latest price in rupees.
             */
            competitor_price: number;
            /**
             * Cpi
             * @description Competitor price index: competitor price ÷ base price.
             */
            cpi: number;
            /**
             * Gap
             * @description 1 minus CPI: how much cheaper the competitor is (< 0: dearer).
             */
            gap: number;
            /** Is Kvi */
            is_kvi: boolean;
            /** Name */
            name: string;
            /**
             * Price Week
             * @description The week of that price, before the as-of week.
             */
            price_week: number;
            region: components["schemas"]["Region"];
            /** Sku Id */
            sku_id: string;
            /** Subcategory */
            subcategory: string;
            /**
             * Undercut
             * @description A KVI whose CPI is below 1 minus the undercut threshold.
             */
            undercut: boolean;
        };
        /**
         * CompetitorGaps
         * @description The gaps for a scope, widest first, with the company-policy rules they were judged by.
         */
        CompetitorGaps: {
            /** As Of Week */
            as_of_week: number;
            /** Gaps */
            gaps: components["schemas"]["CompetitorGap"][];
            /**
             * Kvi Price Tolerance
             * @description How far above the competitor a KVI promo price may sit, when enabled.
             */
            kvi_price_tolerance: number;
            /** Undercut Threshold */
            undercut_threshold: number;
        };
        /**
         * CompetitorReaction
         * @description The competitor-reaction scenario (F-09 AC2, ADR 0045): in each run, each plan line's
         *     competitor matches its discount with this probability, independently of the other lines.
         */
        CompetitorReaction: {
            /**
             * Match Probability
             * @description Chance, per plan line and run, that the competitor matches our discount.
             */
            match_probability: number;
        };
        /** Complement */
        Complement: {
            /**
             * Lift
             * @description P(both in a basket) / (P(one) x P(other)).
             */
            lift: number;
            /** Sku Id */
            sku_id: string;
            /** Std Error */
            std_error: number | null;
            /**
             * Support
             * @description Share of baskets holding both SKUs.
             */
            support: number;
            /**
             * Theta
             * @description Cross-price effect, or null if not estimable.
             */
            theta: number | null;
        };
        /**
         * ConstraintCheck
         * @description The final plan revision's hard constraints on its plan-time values (ADR 0012).
         * @enum {string}
         */
        ConstraintCheck: "passed" | "failed" | "infeasible" | "no_plan";
        /**
         * ConstraintKind
         * @description A plan-level constraint the optimiser enforces (ADR 0036, ADR 0038).
         * @enum {string}
         */
        ConstraintKind: "marketing_budget" | "minimum_margin" | "margin_floor" | "max_promoted_skus" | "regional_budget" | "clearance_target" | "kvi_price_tolerance";
        /**
         * ConstraintSource
         * @description Who set a constraint: only the brief's constraints may be relaxed (ADR 0007).
         * @enum {string}
         */
        ConstraintSource: "brief" | "company_policy";
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /**
             * Brief
             * @description The brief, in plain English.
             */
            brief: string;
        };
        /**
         * DecisionKind
         * @enum {string}
         */
        DecisionKind: "approved" | "rejected";
        /**
         * DecisionMade
         * @description A decision taken in the graph: a route a node chose, or a human's approve or reject.
         */
        DecisionMade: {
            /** Decision */
            decision: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "decision";
            /** Summary */
            summary: string;
        };
        /** EvalReport */
        EvalReport: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Metrics */
            metrics: components["schemas"]["Metric"][];
            /** Planning Settings */
            planning_settings: {
                [key: string]: unknown;
            };
            /** Provider */
            provider: string;
            /** Runs Per Scenario */
            runs_per_scenario: number;
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioResult"][];
            /** World Seed */
            world_seed: number;
        };
        /**
         * ExplainerRun
         * @description One run of the Explainer: the explanation a plan revision waited for approval with.
         */
        ExplainerRun: {
            fallback_reason: components["schemas"]["FallbackReason"] | null;
            /** Revision */
            revision: number;
            source: components["schemas"]["ExplanationSource"];
        };
        /**
         * ExplanationSource
         * @enum {string}
         */
        ExplanationSource: "llm" | "template";
        /**
         * FallbackReason
         * @description Why the template explained a plan revision instead of the LLM.
         * @enum {string}
         */
        FallbackReason: "ungrounded" | "invalid_answer" | "llm_unavailable";
        /**
         * FieldMatch
         * @description One labelled planning-request field against what the final request reads (#55).
         */
        FieldMatch: {
            /** Expected */
            expected: string;
            /** Field */
            field: string;
            /** Got */
            got: string | null;
            /** Matched */
            matched: boolean;
        };
        /**
         * FindingRaised
         * @description Something the Critic found in the plan.
         */
        FindingRaised: {
            /** Code */
            code: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "finding";
            /** Message */
            message: string;
            /** Source */
            source: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthChecks */
        HealthChecks: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
            /**
             * Model Registry
             * @enum {string}
             */
            model_registry: "ok" | "missing";
        };
        /** HealthResponse */
        HealthResponse: {
            checks: components["schemas"]["HealthChecks"];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
        };
        /**
         * InfeasibilityCheck
         * @description Whether an infeasible scenario's final revision says so, names what binds and proposes
         *     a relaxation (AG-06, #55).
         */
        InfeasibilityCheck: {
            /** Binding Named */
            binding_named: boolean;
            /** Declared */
            declared: boolean;
            /** Passed */
            passed: boolean;
            /** Relaxation */
            relaxation: boolean;
            /** Revision */
            revision: number | null;
        };
        /** InventoryReport */
        InventoryReport: {
            /** As Of Week */
            as_of_week: number;
            /** Overstock Threshold Days */
            overstock_threshold_days: number;
            /** Snapshot Week */
            snapshot_week: number;
            /** Statuses */
            statuses: components["schemas"]["InventoryRow"][];
        };
        /** InventoryRow */
        InventoryRow: {
            /** Available Stock */
            available_stock: number;
            /** Category */
            category: string;
            /** Days Of Cover */
            days_of_cover: number;
            /** Is Overstock */
            is_overstock: boolean;
            /** Name */
            name: string;
            /** On Hand */
            on_hand: number;
            /** On Order */
            on_order: number;
            region: components["schemas"]["Region"];
            /** Safety Stock */
            safety_stock: number;
            /** Sku Id */
            sku_id: string;
        };
        JsonValue: unknown;
        /**
         * LineChange
         * @description A plan line whose SKU and region are in both revisions but whose decision changed.
         */
        LineChange: {
            after: components["schemas"]["PlanRevisionLine"];
            before: components["schemas"]["PlanRevisionLine"];
            /** Fields */
            fields: string[];
            region: components["schemas"]["Region"];
            /** Sku Id */
            sku_id: string;
        };
        /**
         * LineCrossEffect
         * @description Another SKU a plan line moves in its region, as the relations calculators give it
         *     (ADR 0033): a fall in profit is cannibalisation, a rise is halo.
         */
        LineCrossEffect: {
            /** Profit Change */
            profit_change: number;
            /** Sku Id */
            sku_id: string;
            /** Units Change Pct */
            units_change_pct: number;
        };
        /**
         * LineSimulation
         * @description One plan line's simulated ranges, identified by its SKU and region.
         */
        LineSimulation: {
            gross_profit: components["schemas"]["Percentiles"];
            margin: components["schemas"]["Percentiles"];
            promo_spend: components["schemas"]["Percentiles"];
            region: components["schemas"]["Region"];
            revenue: components["schemas"]["Percentiles"];
            sell_through: components["schemas"]["Percentiles"] | null;
            /** Sku Id */
            sku_id: string;
            /** Stockout Probability */
            stockout_probability: number;
            units: components["schemas"]["Percentiles"];
        };
        /**
         * Mechanism
         * @enum {string}
         */
        Mechanism: "PCT_OFF" | "BOGO" | "BUNDLE" | "FIXED_PRICE";
        /**
         * MechanismOption
         * @description One promo option's expected numbers, as its prediction gave them (rupees, units over
         *     its promo weeks; a BUNDLE's money fields include its partner).
         */
        MechanismOption: {
            /** Anchor Sku Id */
            anchor_sku_id: string;
            /** Basket Lift */
            basket_lift?: number | null;
            /** Cannibalised Profit */
            cannibalised_profit: number;
            /** Clearance Value */
            clearance_value: number;
            /** Effective Price */
            effective_price: number;
            /** Gross Profit */
            gross_profit: number;
            /** Halo Profit */
            halo_profit: number;
            /** Incremental Profit */
            incremental_profit: number;
            /** Margin */
            margin: number;
            option: components["schemas"]["PlanLine"];
            /** Partner Effective Price */
            partner_effective_price?: number | null;
            /** Partner Sku Id */
            partner_sku_id?: string | null;
            /** Promo Cost */
            promo_cost: number;
            /** Revenue */
            revenue: number;
            /** Units */
            units: number;
            /** Value */
            value: number;
        };
        /**
         * MechanismOutcome
         * @description One mechanism in a comparison: its best option, or why it has none.
         */
        MechanismOutcome: {
            best: components["schemas"]["MechanismOption"] | null;
            /**
             * Chosen
             * @default false
             */
            chosen: boolean;
            mechanism: components["schemas"]["Mechanism"];
            /**
             * Unavailable
             * @default []
             */
            unavailable: components["schemas"]["PruneReason"][];
        };
        /** Metric */
        Metric: {
            /** Aim */
            aim?: number | null;
            /**
             * Breakdown
             * @default {}
             */
            breakdown: {
                [key: string]: number;
            };
            /** Count */
            count: number;
            /** Direction */
            direction?: ("at_least" | "at_most") | null;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Of */
            of: number;
            /** Passed */
            passed?: boolean | null;
            /** Target */
            target?: number | null;
            /**
             * Unit
             * @default share
             * @enum {string}
             */
            unit: "share" | "seconds" | "rupees";
            /** Value */
            value: number | null;
        };
        /**
         * ModelEntry
         * @description One registered model version; `live` marks the one the API is serving.
         */
        ModelEntry: {
            /** As Of Week */
            as_of_week: number;
            kind: components["schemas"]["ModelKind"];
            /** Live */
            live: boolean;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /**
             * Trained At
             * Format: date-time
             */
            trained_at: string;
            /** Version */
            version: number;
        };
        /**
         * ModelKind
         * @enum {string}
         */
        ModelKind: "demand" | "relations";
        /**
         * ModelList
         * @description Registered models, newest first.
         */
        ModelList: {
            /** Models */
            models: components["schemas"]["ModelEntry"][];
        };
        /**
         * ModelVersion
         * @description The registered model that produced the numbers, so a plan can be traced to it.
         */
        ModelVersion: {
            /** As Of Week */
            as_of_week: number;
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /** Version */
            version: number;
        };
        /**
         * NodeFinished
         * @description A graph node's run ended.
         */
        NodeFinished: {
            /** Duration Ms */
            duration_ms: number;
            /** Error */
            error?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "node_finished";
            outcome: components["schemas"]["NodeOutcome"];
        };
        /**
         * NodeOutcome
         * @description How a node's run ended: it finished, paused at an interrupt, or raised.
         * @enum {string}
         */
        NodeOutcome: "completed" | "interrupted" | "failed";
        /**
         * NodeStarted
         * @description A graph node started running (again, when an interrupted node resumes).
         */
        NodeStarted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "node_started";
        };
        /**
         * NotSelectedOption
         * @description The best option of a SKU and region with no plan line, and why it was left out.
         */
        NotSelectedOption: {
            /**
             * Cannibalises
             * @default []
             */
            cannibalises: string[];
            option: components["schemas"]["PlanLine"];
            /** Reasons */
            reasons: components["schemas"]["NotSelectedReason"][];
            /** Value */
            value: number;
        };
        /**
         * NotSelectedReason
         * @description Why a promo option is not in the plan: a rule it breaks alone or added to the plan.
         * @enum {string}
         */
        NotSelectedReason: "low_uplift" | "out_of_stock" | "breaks_policy" | "over_budget" | "over_regional_budget" | "breaks_margin" | "max_promoted_skus" | "misses_clearance_target" | "breaks_kvi_tolerance" | "cannibalises" | "time_limit";
        OpenIssue: components["schemas"]["Violation"] | components["schemas"]["RiskFinding"];
        /**
         * OracleScore
         * @description The final plan's true expected outcome (ADR 0011, ADR 0017).
         */
        OracleScore: {
            /** Blended Margin */
            blended_margin: number | null;
            /** Breaches */
            breaches: components["schemas"]["Breach"][];
            /** Clearance Value */
            clearance_value: number;
            /** Incremental Profit */
            incremental_profit: number;
            /** Promo Cost */
            promo_cost: number;
            /** Stock Capped Lines */
            stock_capped_lines: number;
        };
        /**
         * Percentiles
         * @description The 10th, 50th and 90th percentiles of one simulated metric across the runs.
         */
        Percentiles: {
            /** P10 */
            p10: number;
            /** P50 */
            p50: number;
            /** P90 */
            p90: number;
        };
        /**
         * PlanDecision
         * @description One human decision on one plan revision: an approval or a rejection with its reason.
         *     Every decision is kept, in order, as the session's audit trail (SF-04, ADR 0046).
         */
        PlanDecision: {
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            decision: components["schemas"]["DecisionKind"];
            /** Reason */
            reason?: string | null;
            /** Revision Number */
            revision_number: number;
        };
        /**
         * PlanExplanation
         * @description What the Explainer wrote for one plan revision.
         */
        PlanExplanation: {
            /** Changes */
            changes?: string | null;
            /**
             * Competitor Response
             * @default []
             */
            competitor_response: string[];
            fallback_reason?: components["schemas"]["FallbackReason"] | null;
            /**
             * Rationales
             * @default []
             */
            rationales: string[];
            source: components["schemas"]["ExplanationSource"];
            /** Summary */
            summary: string;
        };
        /**
         * PlanLine
         * @description A promo option selected into a promo plan: one (SKU, region) decision (ADR 0004).
         */
        PlanLine: {
            /** Bundle Partner Sku Id */
            bundle_partner_sku_id?: string | null;
            /** Depth Pct */
            depth_pct: number;
            /** Duration Weeks */
            duration_weeks: number;
            mechanism: components["schemas"]["Mechanism"];
            region: components["schemas"]["Region"];
            /** Sku Id */
            sku_id: string;
            /** Start Week */
            start_week: number;
            target_segment: components["schemas"]["TargetSegment"];
        };
        /**
         * PlanQuality
         * @description A scored final plan against the rule-based baseline and the best plan (ADR 0063).
         */
        PlanQuality: {
            best: components["schemas"]["BestPlanSummary"];
            /** Objective */
            objective: number;
            /** Regret */
            regret: number | null;
            /** Regret Rupees */
            regret_rupees: number | null;
            rule_based: components["schemas"]["RuleBasedSummary"];
            /**
             * Versus Rule Based
             * @enum {string}
             */
            versus_rule_based: "beats" | "ties" | "loses";
        };
        /**
         * PlanRevision
         * @description One numbered version of the promo plan within a planning session.
         */
        PlanRevision: {
            /**
             * Binding Constraints
             * @default []
             */
            binding_constraints: components["schemas"]["BindingConstraint"][];
            /**
             * Clearance Shortfalls
             * @default []
             */
            clearance_shortfalls: components["schemas"]["ClearanceShortfall"][];
            diff?: components["schemas"]["RevisionDiff"] | null;
            explanation?: components["schemas"]["PlanExplanation"] | null;
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["PlanRevisionLine"][];
            /**
             * Not Selected
             * @default []
             */
            not_selected: components["schemas"]["NotSelectedOption"][];
            /** Number */
            number: number;
            /** Objective */
            objective?: number | null;
            /**
             * Open Issues
             * @default []
             */
            open_issues: components["schemas"]["OpenIssue"][];
            /**
             * Policy Findings
             * @default []
             */
            policy_findings: components["schemas"]["PolicyFinding"][];
            relaxation?: components["schemas"]["Relaxation"] | null;
            simulation?: components["schemas"]["PlanSimulation"] | null;
            solver_status?: components["schemas"]["SolveStatus"] | null;
        };
        /**
         * PlanRevisionLine
         * @description A plan line with the expected numbers the planning tool computed for it (rupees).
         */
        PlanRevisionLine: {
            /** Baseline Units */
            baseline_units?: number | null;
            /**
             * Cross Effects
             * @default []
             */
            cross_effects: components["schemas"]["LineCrossEffect"][];
            /** Expected Incremental Profit */
            expected_incremental_profit: number;
            /** Expected Units */
            expected_units: number;
            line: components["schemas"]["PlanLine"];
            /**
             * Mechanism Comparison
             * @default []
             */
            mechanism_comparison: components["schemas"]["MechanismOutcome"][];
            /** Promo Cost */
            promo_cost: number;
            /**
             * Segments
             * @default []
             */
            segments: components["schemas"]["SegmentUplift"][];
            /** Uplift Pct */
            uplift_pct?: number | null;
            why_chosen?: components["schemas"]["WhyChosen"] | null;
        };
        /**
         * PlanSimulation
         * @description What `simulate` returns for a promo plan, and what a plan revision stores.
         */
        PlanSimulation: {
            competitor_reaction?: components["schemas"]["CompetitorReaction"] | null;
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["LineSimulation"][];
            /** N Runs */
            n_runs: number;
            /**
             * Regions
             * @default []
             */
            regions: components["schemas"]["RegionStockout"][];
            /** Seed */
            seed: number;
            total: components["schemas"]["SimulatedOutcomes"];
        };
        /**
         * PlanSimulationResponse
         * @description A plan revision's new simulation, now stored against it in place of the old one.
         */
        PlanSimulationResponse: {
            /** As Of Week */
            as_of_week: number;
            demand_model: components["schemas"]["ModelVersion"];
            /** Revision Number */
            revision_number: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            simulation: components["schemas"]["PlanSimulation"];
        };
        /**
         * PlanningRequest
         * @description Money is in rupees (ADR 0015). The brief's optional constraints may only tighten
         *     company policy; a value that would loosen it is kept here as read, and planning applies
         *     the policy value instead and flags it (ADR 0007, ADR 0040).
         */
        PlanningRequest: {
            /** As Of Week */
            as_of_week: number;
            /**
             * Clearance Targets
             * @default []
             */
            clearance_targets: components["schemas"]["ClearanceTarget"][];
            /** Kvi Price Tolerance */
            kvi_price_tolerance?: number | null;
            /** Marketing Budget */
            marketing_budget: number;
            /** Max Promoted Skus Per Category Per Region */
            max_promoted_skus_per_category_per_region?: number | null;
            /** Min Margin */
            min_margin?: number | null;
            promo_window: components["schemas"]["PromoWindow"];
            /** Regional Budget Caps */
            regional_budget_caps?: {
                [key: string]: number;
            };
            scope: components["schemas"]["Scope"];
        };
        /**
         * PolicyFinding
         * @description A brief value that would loosen company policy: planning keeps the policy value and
         *     flags it (ADR 0007, ADR 0040).
         */
        PolicyFinding: {
            /** Applied */
            applied: number;
            /** Field */
            field: string;
            /** Message */
            message: string;
            /** Requested */
            requested: number;
        };
        /** Product */
        Product: {
            /** Base Price */
            base_price: number;
            /** Brand */
            brand: string;
            /** Category */
            category: string;
            /** Is Kvi */
            is_kvi: boolean;
            /** Name */
            name: string;
            /** Pack Size */
            pack_size: string;
            /** Sku Id */
            sku_id: string;
            /** Subcategory */
            subcategory: string;
            /** Unit Cost */
            unit_cost: number;
        };
        /** ProductList */
        ProductList: {
            /** Products */
            products: components["schemas"]["Product"][];
        };
        /**
         * PromoWindow
         * @description The future weeks, inclusive, in which a plan's promotions must start and end.
         */
        PromoWindow: {
            /** End Week */
            end_week: number;
            /** Start Week */
            start_week: number;
        };
        /** PropertyResult */
        PropertyResult: {
            /** Detail */
            detail: string;
            /** Passed */
            passed: boolean;
            /** Property */
            property: string;
        };
        /**
         * PruneReason
         * @description Why option generation dropped an enumerated promo option, in the order the rules are
         *     applied (ADR 0035).
         * @enum {string}
         */
        PruneReason: "no_charm_price" | "max_discount" | "below_cost" | "duplicate_price" | "stock" | "partner_stock";
        /**
         * QuestionReason
         * @enum {string}
         */
        QuestionReason: "missing" | "low_confidence" | "ambiguous";
        /**
         * Region
         * @enum {string}
         */
        Region: "North" | "South" | "East" | "West";
        /** RegionList */
        RegionList: {
            /** Regions */
            regions: components["schemas"]["RegionStores"][];
        };
        /** RegionStockout */
        RegionStockout: {
            region: components["schemas"]["Region"];
            /** Stockout Probability */
            stockout_probability: number;
        };
        /** RegionStores */
        RegionStores: {
            region: components["schemas"]["Region"];
            /** Stores */
            stores: components["schemas"]["Store"][];
        };
        /**
         * RejectRequest
         * @description Reject a plan revision, the session's latest, with the reason (ADR 0046).
         */
        RejectRequest: {
            /**
             * Reason
             * @description Why, in plain English.
             */
            reason: string;
            /**
             * Revision Number
             * @description The plan revision being rejected.
             */
            revision_number: number;
        };
        /**
         * RelationsResponse
         * @description A SKU's substitutes (strongest first) and complements (highest lift first).
         */
        RelationsResponse: {
            /** Complements */
            complements: components["schemas"]["Complement"][];
            model: components["schemas"]["ModelVersion"];
            /** Sku Id */
            sku_id: string;
            /** Substitutes */
            substitutes: components["schemas"]["Substitute"][];
        };
        /**
         * Relaxation
         * @description The smallest change to the brief's constraints that makes an infeasible request
         *     feasible: the least sum of each change as a share of the brief's value (ADR 0044).
         */
        Relaxation: {
            /** Changes */
            changes: components["schemas"]["RelaxedConstraint"][];
            /** Policy Binds */
            policy_binds: boolean;
            /** Proven */
            proven: boolean;
        };
        /**
         * RelaxedConstraint
         * @description One brief constraint the relaxation changes, and by how much (ADR 0044).
         */
        RelaxedConstraint: {
            /** Change */
            change: number;
            /** Current */
            current: number;
            kind: components["schemas"]["ConstraintKind"];
            /** Policy Allows */
            policy_allows?: number | null;
            region?: components["schemas"]["Region"] | null;
            /** Relaxed */
            relaxed: number | null;
            /** Sku Id */
            sku_id?: string | null;
            /** @default brief */
            source: components["schemas"]["ConstraintSource"];
        };
        /**
         * RequestChange
         * @description A planning-request field an amendment changed, shown as the explanation may cite it.
         */
        RequestChange: {
            /** After */
            after: string;
            /** Before */
            before: string;
            /** Field */
            field: string;
        };
        /**
         * RevisionDiff
         * @description What changed from the previous plan revision (AG-05, ADR 0052): plan lines matched by
         *     (SKU, region), the objective and promo-cost deltas, and the planning-request changes.
         */
        RevisionDiff: {
            /**
             * Added
             * @default []
             */
            added: components["schemas"]["PlanRevisionLine"][];
            /**
             * Changed
             * @default []
             */
            changed: components["schemas"]["LineChange"][];
            /** From Revision */
            from_revision: number;
            /** Objective After */
            objective_after?: number | null;
            /** Objective Before */
            objective_before?: number | null;
            /** Objective Delta */
            objective_delta?: number | null;
            /**
             * Promo Cost After
             * @default 0
             */
            promo_cost_after: number;
            /**
             * Promo Cost Before
             * @default 0
             */
            promo_cost_before: number;
            /**
             * Promo Cost Delta
             * @default 0
             */
            promo_cost_delta: number;
            /**
             * Removed
             * @default []
             */
            removed: components["schemas"]["PlanRevisionLine"][];
            /**
             * Request Changes
             * @default []
             */
            request_changes: components["schemas"]["RequestChange"][];
            /**
             * Unchanged
             * @default 0
             */
            unchanged: number;
        };
        /** RevisionSummary */
        RevisionSummary: {
            /** Lines */
            lines: number;
            /** Marketing Budget */
            marketing_budget: number;
            /** Number */
            number: number;
            /** Objective */
            objective: number | null;
            /** Promo Cost */
            promo_cost: number;
            /** Regions */
            regions: components["schemas"]["Region"][];
            /**
             * Sku Ids
             * @default []
             */
            sku_ids: string[];
            solver_status: components["schemas"]["SolveStatus"] | null;
        };
        /**
         * RiskCode
         * @enum {string}
         */
        RiskCode: "OVER_CONCENTRATION" | "HEAVY_CANNIBALISATION" | "STOCKOUT_RISK";
        /**
         * RiskFinding
         * @description One risk the Critic's review found, with feedback specific enough for the planner to act
         *     on. Its numbers come from the plan's tool outputs, never from the LLM.
         */
        RiskFinding: {
            /** Actual */
            actual: number;
            /** Category */
            category?: string | null;
            code: components["schemas"]["RiskCode"];
            /** Feedback */
            feedback: string;
            /**
             * Kind
             * @default risk
             * @constant
             */
            kind: "risk";
            /** Limit */
            limit: number;
            /** Message */
            message: string;
            region?: components["schemas"]["Region"] | null;
            /** Sku Id */
            sku_id?: string | null;
        };
        /**
         * RuleBasedSummary
         * @description The rule-based baseline (SPEC §12.2, ADR 0063): 20% off the top 10 sellers in scope,
         *     to All customers, over the whole promo window, dropped from the bottom until its expected
         *     promo cost fits the budget.
         */
        RuleBasedSummary: {
            /** Dropped Sku Ids */
            dropped_sku_ids: string[];
            /** Expected Promo Cost */
            expected_promo_cost: number;
            /** Lines */
            lines: number;
            /** Objective */
            objective: number;
            /** Sku Ids */
            sku_ids: string[];
        };
        /**
         * RunOutcome
         * @description How a scenario's session ended.
         * @enum {string}
         */
        RunOutcome: "planned" | "awaiting_clarification" | "failed";
        /** RunResult */
        RunResult: {
            /**
             * Amendments Applied
             * @default 0
             */
            amendments_applied: number;
            /**
             * Cassette Misses
             * @default []
             */
            cassette_misses: string[];
            clarification?: components["schemas"]["ClarificationCheck"] | null;
            /** @default no_plan */
            constraints: components["schemas"]["ConstraintCheck"];
            /**
             * Duration S
             * @default 0
             */
            duration_s: number;
            /** Error */
            error?: string | null;
            /**
             * Explanations
             * @default []
             */
            explanations: components["schemas"]["ExplainerRun"][];
            /**
             * Extraction
             * @default []
             */
            extraction: components["schemas"]["FieldMatch"][];
            /**
             * Fallbacks
             * @default []
             */
            fallbacks: string[];
            /**
             * Flagged
             * @default []
             */
            flagged: string[];
            infeasibility?: components["schemas"]["InfeasibilityCheck"] | null;
            oracle?: components["schemas"]["OracleScore"] | null;
            outcome: components["schemas"]["RunOutcome"];
            /**
             * Properties
             * @default []
             */
            properties: components["schemas"]["PropertyResult"][];
            quality?: components["schemas"]["PlanQuality"] | null;
            /**
             * Questions Asked
             * @default []
             */
            questions_asked: string[];
            revision?: components["schemas"]["RevisionSummary"] | null;
            /**
             * Route
             * @default []
             */
            route: string[];
            /** Run */
            run: number;
            /**
             * Session S
             * @default 0
             */
            session_s: number;
            /**
             * Unneeded Asks
             * @default []
             */
            unneeded_asks: string[];
            /**
             * @default {
             *       "calls": 0,
             *       "cost_inr": 0,
             *       "cost_usd": 0,
             *       "input_tokens": 0,
             *       "output_tokens": 0,
             *       "unpriced_models": []
             *     }
             */
            usage: components["schemas"]["SessionUsage"];
            /**
             * Violations
             * @default []
             */
            violations: components["schemas"]["Violation"][];
        };
        /** ScenarioResult */
        ScenarioResult: {
            /** As Of Week */
            as_of_week: number;
            /** Consistency */
            consistency?: number | null;
            /** Group */
            group: string;
            /** Name */
            name: string;
            /** Passed */
            passed: boolean;
            /** Runs */
            runs: components["schemas"]["RunResult"][];
            /** Seed */
            seed: number;
        };
        /**
         * Scope
         * @description The regions and categories a planning request covers, optionally narrowed to SKUs.
         */
        Scope: {
            /** Categories */
            categories: string[];
            /** Regions */
            regions: components["schemas"]["Region"][];
            /**
             * Sku Ids
             * @default []
             */
            sku_ids: string[];
        };
        /**
         * Segment
         * @description A behavioural customer group; never defined by protected attributes.
         * @enum {string}
         */
        Segment: "Value Seekers" | "Families" | "Premium" | "Young Urban";
        /**
         * SegmentUplift
         * @description A plan line's expected units in one customer segment against its no-promotion baseline,
         *     the anchor SKU's over the promo weeks (F-03 AC2).
         */
        SegmentUplift: {
            /** Baseline Units */
            baseline_units: number;
            segment: components["schemas"]["Segment"];
            /** Units */
            units: number;
            /** Uplift Pct */
            uplift_pct: number | null;
        };
        /** SelectionReason */
        SelectionReason: {
            /** Amount */
            amount: number;
            code: components["schemas"]["SelectionReasonCode"];
        };
        /**
         * SelectionReasonCode
         * @description A positive part of a plan line's value (ADR 0005, ADR 0035), or the clearance target it
         *     helps meet (ADR 0040).
         * @enum {string}
         */
        SelectionReasonCode: "incremental_profit" | "clearance_value" | "halo" | "clearance_target";
        /** SessionCreated */
        SessionCreated: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /**
         * SessionResponse
         * @description One planning session's read model: status, brief, planning request, latest revision.
         */
        SessionResponse: {
            /**
             * Amendments
             * @description Every amendment to the planning request, oldest first (ADR 0052).
             */
            amendments: components["schemas"]["Amendment"][];
            /**
             * Assumptions
             * @description How the Context agent read the brief, each with its source and confidence (ADR 0048).
             */
            assumptions: components["schemas"]["Assumption"][];
            /** Brief */
            brief: string;
            /**
             * Clarifications
             * @description Every question answered so far, oldest first.
             */
            clarifications: components["schemas"]["Clarification"][];
            /**
             * Decisions
             * @description Every approval and rejection, oldest first: the session's audit trail.
             */
            decisions: components["schemas"]["PlanDecision"][];
            /** Error */
            error: string | null;
            plan_revision: components["schemas"]["PlanRevision"] | null;
            planning_request: components["schemas"]["PlanningRequest"] | null;
            /**
             * Questions
             * @description The clarification questions waiting for an answer (awaiting_clarification).
             */
            questions: components["schemas"]["ClarificationQuestion"][];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["SessionStatus"];
            /** @description What the session's LLM calls used and cost: the sums of its token-usage trace events (ADR 0047). */
            usage: components["schemas"]["SessionUsage"];
        };
        /**
         * SessionStatus
         * @description Every status a planning session can have (ADR 0046).
         *
         *     planning -> awaiting_approval -> approved (final) or rejected (open for amendments); any
         *     failure while planning -> failed; planning -> awaiting_clarification -> planning when the
         *     questions are answered (ADR 0048); awaiting_approval or rejected -> planning when the
         *     request is amended (ADR 0052).
         * @enum {string}
         */
        SessionStatus: "planning" | "awaiting_clarification" | "awaiting_approval" | "approved" | "rejected" | "failed";
        /**
         * SessionUsage
         * @description What a planning session's LLM calls used and cost: the sums of its token-usage events.
         */
        SessionUsage: {
            /**
             * Calls
             * @default 0
             */
            calls: number;
            /**
             * Cost Inr
             * @default 0
             */
            cost_inr: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Unpriced Models
             * @default []
             */
            unpriced_models: string[];
        };
        /**
         * SimulatePlanRequest
         * @description Re-simulate a session's latest plan revision (ADR 0043), optionally against a
         *     competitor reaction (ADR 0045). The seed is configuration.
         */
        SimulatePlanRequest: {
            /** @description The competitor-reaction scenario; omit or null for a competitor that never reacts. */
            competitor_reaction?: components["schemas"]["CompetitorReaction"] | null;
            /**
             * N Runs
             * @description Runs to simulate; omit for the configured default (SIMULATION_RUNS).
             */
            n_runs?: number | null;
        };
        /**
         * SimulatedOutcomes
         * @description Ranges over the promo weeks, units capped at pooled available stock (ADR 0004, 0011).
         *
         *     Units and sell-through are the anchor SKU's; revenue, gross profit and promo spend
         *     include a BUNDLE's partner (ADR 0017). Margin is gross profit over revenue in each run
         *     (0 in a run with no revenue). Sell-through is None when there is no available stock.
         */
        SimulatedOutcomes: {
            gross_profit: components["schemas"]["Percentiles"];
            margin: components["schemas"]["Percentiles"];
            promo_spend: components["schemas"]["Percentiles"];
            revenue: components["schemas"]["Percentiles"];
            sell_through: components["schemas"]["Percentiles"] | null;
            units: components["schemas"]["Percentiles"];
        };
        /**
         * SolveStatus
         * @enum {string}
         */
        SolveStatus: "OPTIMAL" | "FEASIBLE" | "INFEASIBLE";
        /** Store */
        Store: {
            /** City */
            city: string;
            /** Segment Mix */
            segment_mix: {
                [key: string]: number;
            };
            /** Store Id */
            store_id: string;
        };
        /** Substitute */
        Substitute: {
            /** Q Value */
            q_value: number;
            /** Sku Id */
            sku_id: string;
            /** Std Error */
            std_error: number;
            /**
             * Theta
             * @description Cross-price effect: positive for a substitute.
             */
            theta: number;
        };
        /**
         * TargetSegment
         * @description Who a plan line is offered to: one segment exclusively, or All customers (ADR 0006).
         * @enum {string}
         */
        TargetSegment: "Value Seekers" | "Families" | "Premium" | "Young Urban" | "All customers";
        /**
         * TokensUsed
         * @description One billed LLM call: its model, tokens and cost, priced when it was made.
         */
        TokensUsed: {
            /** Cost Inr */
            cost_inr: number | null;
            /** Cost Usd */
            cost_usd: number | null;
            /** Input Tokens */
            input_tokens: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "token_usage";
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens: number;
        };
        /**
         * ToolCalled
         * @description A deterministic tool was called: its arguments and a summary of what it returned.
         */
        ToolCalled: {
            arguments: components["schemas"]["JsonValue"];
            /** Error Code */
            error_code?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "tool_called";
            /** Ok */
            ok: boolean;
            result_summary: components["schemas"]["JsonValue"];
            /** Tool */
            tool: string;
        };
        /**
         * TraceEvent
         * @description One step of a planning session's trace.
         */
        TraceEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Id */
            id: number;
            /** Node */
            node: string | null;
            payload: components["schemas"]["TracePayload"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        TracePayload: components["schemas"]["NodeStarted"] | components["schemas"]["NodeFinished"] | components["schemas"]["ToolCalled"] | components["schemas"]["DecisionMade"] | components["schemas"]["ClarificationAsked"] | components["schemas"]["FindingRaised"] | components["schemas"]["TokensUsed"];
        /**
         * TraceStreamEnd
         * @description The last event of a session's trace stream (`event: end`): the session is final, so no
         *     more trace events can come (ADR 0047).
         */
        TraceStreamEnd: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["SessionStatus"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Violation
         * @description One broken hard constraint, specific enough for the planner to fix.
         */
        Violation: {
            /** Actual */
            actual?: number | null;
            code: components["schemas"]["ViolationCode"];
            /**
             * Kind
             * @default violation
             * @constant
             */
            kind: "violation";
            /** Limit */
            limit?: number | null;
            /** Message */
            message: string;
            region?: components["schemas"]["Region"] | null;
            /** Sku Id */
            sku_id?: string | null;
        };
        /**
         * ViolationCode
         * @enum {string}
         */
        ViolationCode: "BUDGET" | "REGIONAL_BUDGET" | "MIN_MARGIN" | "MARGIN_FLOOR" | "STOCK" | "MAX_DISCOUNT" | "BELOW_COST" | "WINDOW" | "MAX_SKUS" | "DUPLICATE_LINE" | "CLEARANCE_TARGET" | "KVI_TOLERANCE";
        /**
         * WhyChosen
         * @description Why a plan line was chosen: the positive parts of its value, what it is worth alone,
         *     and whether it is the best option the optimiser could pick for its SKU and region.
         */
        WhyChosen: {
            /** Best For Sku Region */
            best_for_sku_region: boolean;
            /** Reasons */
            reasons: components["schemas"]["SelectionReason"][];
            /** Value */
            value: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_products_api_catalog_products_get: {
        parameters: {
            query?: {
                category?: string | null;
                kvi_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_regions_api_catalog_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionList"];
                };
            };
        };
    };
    competitor_gaps_api_competitors_gaps_get: {
        parameters: {
            query?: {
                /** @description Defaults to the data's default as-of week. */
                as_of_week?: number | null;
                region?: components["schemas"]["Region"] | null;
                category?: string | null;
                kvi_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitorGaps"];
                };
            };
            /** @description No data is loaded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_api_evals_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalReport"];
                };
            };
            /** @description No eval report this version can read */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    inventory_api_inventory_get: {
        parameters: {
            query?: {
                /** @description Defaults to the data's default as-of week. */
                as_of_week?: number | null;
                region?: components["schemas"]["Region"] | null;
                category?: string | null;
                overstocked_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryReport"];
                };
            };
            /** @description No data is loaded for the week */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
        };
    };
    retrain_api_models_retrain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelEntry"];
                };
            };
            /** @description A retrain is running or no data */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    simulate_plan_api_plans__session_id__simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulatePlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSimulationResponse"];
                };
            };
            /** @description Unknown session, or a session without a plan revision yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The session is approved, so its plan is final, or the latest demand model cannot simulate the stored plan */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No trained demand model, or no inventory snapshot for the planning request's as-of week */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_relations_api_relations__sku_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationsResponse"];
                };
            };
            /** @description No such SKU */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description No relations model fitted on the live demand model */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planning is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unknown session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    amend_session_api_sessions__session_id__amend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unknown session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The session is not awaiting approval or rejected, or (accept_relaxation) its latest revision has no relaxation */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planning is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve_session_api_sessions__session_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unknown session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The session is not awaiting approval, the revision is not its latest, or (approve) the revision is infeasible */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planning is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clarify_session_api_sessions__session_id__clarify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClarifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unknown session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The session is not awaiting clarification */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planning is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    session_events_api_sessions__session_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "last-event-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Unknown session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_session_api_sessions__session_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unknown session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The session is not awaiting approval, the revision is not its latest, or (approve) the revision is infeasible */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Planning is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
